/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd_mensajeria.GUI;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextField;
import sd_conexion_bd.Servicios;

/**
 *
 * @author Kattya Desiderio
 */
public class Buscar_Contacto extends javax.swing.JFrame {
    JList contactosDelUsuario;
    Servicios serv;
    int user_id;
    /**
     * Creates new form Buscar_Contacto
     */
    public Buscar_Contacto(Servicios s, JList contactos_lista, int userID) {
        super("Java Chat");
        initComponents();
        this.setLocationRelativeTo(null);
        this.contactosDelUsuario = contactos_lista;
        this.serv=s;
        this.user_id=userID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        opcion_busqueda = new javax.swing.JComboBox();
        tipiar_busqueda = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultado_busqueda = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(419, 495));
        setMinimumSize(new java.awt.Dimension(419, 495));
        setPreferredSize(new java.awt.Dimension(419, 495));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Buscar Contacto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 342, 58);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Busquedad por:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 111, 17);

        opcion_busqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "nombre", "user", "ciudad" }));
        opcion_busqueda.setToolTipText("");
        opcion_busqueda.setName("cmb_criterio"); // NOI18N
        opcion_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_busquedaActionPerformed(evt);
            }
        });
        getContentPane().add(opcion_busqueda);
        opcion_busqueda.setBounds(150, 96, 93, 30);

        tipiar_busqueda.setName("txt_criterio"); // NOI18N
        tipiar_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipiar_busquedaActionPerformed(evt);
            }
        });
        tipiar_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tipiar_busquedaKeyReleased(evt);
            }
        });
        getContentPane().add(tipiar_busqueda);
        tipiar_busqueda.setBounds(150, 140, 200, 40);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 14))); // NOI18N
        jPanel4.setName("Resultado"); // NOI18N

        resultado_busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resultado_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultado_busquedaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(resultado_busqueda);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 200, 380, 220);
        jPanel4.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcion_busquedaActionPerformed

    private void resultado_busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultado_busquedaMouseClicked
        // TODO add your handling code here:
        String contacto = (String)resultado_busqueda.getSelectedValue();
        if (evt.getClickCount() == 2){
            try {
                new Chat(contacto, this.user_id ,this.serv);
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_resultado_busquedaMouseClicked

    private void tipiar_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipiar_busquedaKeyReleased
        // TODO add your handling code here:
        JTextField j =(JTextField)evt.getSource();
        int opcion;
        String str1;
        String str2 = j.getText();
        DefaultListModel model = new DefaultListModel();
        if(!j.getText().equals("")){
            //vslidar opciones de busqueda
            opcion = opcion_busqueda.getSelectedIndex();
            switch(opcion){
                case 0:
                    for(int i=0; i<contactosDelUsuario.getModel().getSize(); i++){
                        str1 = (String)contactosDelUsuario.getModel().getElementAt(i);
                        if(str1.toLowerCase().contains(str2.toLowerCase())){
                            model.addElement(str1);
                        }
                    }
                    break;
                case 1://busqueda por user
                    this.serv.buscarPorUser( this.user_id, str2.toLowerCase(), model);
                    break;
                case 2://busqueda por ciudad
                    this.serv.buscarPorCiudad( this.user_id, str2.toLowerCase(), model);
                    break;
            }
            if(!model.isEmpty()){//lista  con datos para mostrar
                resultado_busqueda.setModel(model);
                resultado_busqueda.setVisible(true);
            }else{
                model.clear();
                resultado_busqueda.setModel(model);
                resultado_busqueda.setVisible(true);
            }
        }else{//
            model.clear();
            resultado_busqueda.setModel(model);
            resultado_busqueda.setVisible(true);
        }
    }//GEN-LAST:event_tipiar_busquedaKeyReleased

    private void tipiar_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipiar_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipiar_busquedaActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox opcion_busqueda;
    private javax.swing.JList resultado_busqueda;
    private javax.swing.JTextField tipiar_busqueda;
    // End of variables declaration//GEN-END:variables
}
